added styles and colorHash function
EmilSroka/CoNDeT pull request #11
Opened 2021-04-12 19:25 UTC by M1LO234

2021-04-12 20:20 UTC, EmilSroka requested changes
Brakuje tych drugich styli które pokazywałeś

2021-04-12 20:20 UTC, EmilSroka commented on library/css/styles.css
> +}
Nie wiem czy ten fragment jest potrzebny. Niech zostanie. I tak trzeba będzie jeszcze przepatrzeć CSS jak już będziemy mieli gotowe tabele

2021-04-12 20:20 UTC, EmilSroka commented on library/src/core/index.js
> +        r = ~~(('0.' + Math.sin(sum + 1).toString().substr(6)) * 210);
`~~` obcina część po przecinku

2021-04-12 20:20 UTC, EmilSroka commented on library/src/core/index.js
> +            hex: hex
Pytanie czy będziemy używać zarówno rgb jak i hex oraz czy będą nam potrzebne same części składowe (r, g lub b)?

2021-04-12 20:40 UTC, EmilSroka approved these changes
LGTM

2021-04-16 07:55 UTC, HubMiz approved these changes

2021-04-16 07:59 UTC, merged