lib: add BaseComponent (WIP)
EmilSroka/CoNDeT pull request #22
Opened 2021-04-23 19:10 UTC by M1LO234

2021-04-24 08:47 UTC, EmilSroka requested changes
Jak coś nie jasne a w dokumentacji jeszcze nie poprawione (spróbuję wieczorem dzisiaj poprawić) to pisz

2021-04-24 08:47 UTC, EmilSroka commented on library/src/ui/index.js
> +        },
Nie powinno być inicjalizacji, bo i tak przy pierwszym użyciu `setState` atrybut `state` zostanie nadpisany. `common` podobnie

2021-04-24 08:47 UTC, EmilSroka commented on library/src/ui/index.js
> +        },
Do `onInit` należy podać `common` i `props`. Dodatkowo `common` należy zapisać w obiekcie nadpisując wartość `this.common`

2021-04-24 08:47 UTC, EmilSroka commented on library/src/ui/index.js
> +        },
`this.ref` jest elementem dom. Więc wywołanie na nim `onUpdate` na 99% wywali type error  
Tutaj też do należy podać `common` i `props` do `this.onUpdate()`  
W sumie to nie wiemy, czy komponent chce aktualizować dzieci. Więc usunąłbym `children.update();`

2021-04-24 08:47 UTC, EmilSroka commented on library/src/ui/index.js
> +        },
Po namyśle, w `destroy` będzie podawany jedynie `common` bez `props`. Poprawię to w dokumentacji  
Przed `children.update();` nie ma `this` więc tworzysz zmienną globalną. Dodatkowo children jest tablicą, więc w praktyce należy:  
1. sprawdzić, czy `this.children` istnieje (minimum, że jest `!= null` co sprawdzi jednocześnie, czy nie jest `undefined`, można sprawdzić też, czy jest tablicą, ale nie wiem, czy jest taka potrzeba, chyba nie)
2. iteracja po elementach tablicy
3. dla każdego wywołanie `update` z przekazanymi common  
`this.onDestroy();` podać `common` a `this.ref.onDestroy();` usunąć (tłumaczyłem dlaczego komentarz wyżej)

2021-04-24 08:47 UTC, EmilSroka commented on library/src/ui/index.js
> +        },
`domReference` -> `ref`

2021-04-24 08:47 UTC, EmilSroka commented on library/src/ui/index.js
> +        },
Same: `domReference` -> `ref`

2021-04-24 08:47 UTC, EmilSroka commented on library/src/ui/index.js
> +        },
And again: `domReference` -> `ref`  
Dodatkowo używanie ternary tutaj wydaje się mało czytelne. W JS operatory logicznie nie zwracają boolean (no może poza `!`) więc lepiej jawnie podawać typy. Ale tutaj masz same porównania które już zwracają `boolean`. Więc możne zwrócić efekt operatorów logiczny bez dodawania `? true : false`  
Co do poprawności algorytmu, to ufam, że działa 😜

2021-04-24 08:47 UTC, EmilSroka commented on library/src/ui/index.js
> +        },
Tutaj też trzeba sprawdzić, czy `this.state` istnieje

2021-04-24 08:47 UTC, EmilSroka commented on library/src/ui/index.js
> +        },
Przed `ref` brakuje `this` (znów odwołanie do global scope, co pokazuje dlaczego w JS jest to taki problem i dlaczego odchodzi się od takiego pisania bibliotek)
![chrome_xrocYLjrGe](https://user-images.githubusercontent.com/40248436/115952764-3ac09680-a4e8-11eb-8b0d-d460333473d4.png)

2021-04-24 08:47 UTC, EmilSroka commented on library/src/ui/index.js
> +        },
Tutaj jak powiedziałem. W dokumentacji poprawię na dwie metody. `appendChild` która będzie przyjmować już gotowy komponent oraz `createChild` która dostanie `props` i referencję do kontruktora komponentu. W obu będzie opcjonalny parametr position.  
Funkcja `createChild` będzie działać tak samo jak `appendChild`, ale utworzy komponent (referencja do konstruktora) oraz wywoła init podając `common` i `props`.  
Poza dodaniem do tablicy `this.children` elementu należy zwalidować, czy tablica istnieje oraz czy podana pozycja nie wykracza poza dopuszczalny zasięg. Jeżeli wykracza, to wstawić na ostatniej pozycji.  
Należy jeszcze dodać `child.ref` w odpowiednie miejsce `this.ref`. Mając tablicę wszystkich komponentów powinno się dać użyć [tego](https://developer.mozilla.org/en-US/docs/Web/API/Node/insertBefore) biorąc `ref` następnego komponentu na liście. Jak jest wstawiany jako ostatni to [`appendChild`](https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild)

2021-04-24 08:47 UTC, EmilSroka commented on library/src/ui/index.js
> +    }
Tutaj też będą dwie metody w takim razie. W pierwszej będzie podawany komponent a w drugiej pozycja (`removeChildAtPosition`).  
`var child = new BaseComponent.init(this.common, props);` do usunięcia.  
1. walidacja listy -> poza zakresem to brak akcji
2. bierzemy element i usuwamy z tablicy (btw, bardzo ciekawe ternary. Ale chyba lepiej jest dać `if`. Nie wszystko co jest krótsze jest też czytelniejsze)  
3. wywołać `destroy` na usuwanym komponencie podając `common`

2021-04-29 12:16 UTC, EmilSroka requested changes
Dwie poprawki i kilka propozycji na refactor do rozważenia

2021-04-29 12:16 UTC, EmilSroka commented on library/src/ui/index.js
> +      this.state.onInit();
W sumie jeżeli `this.state` jest `undefined` na początku, to zawsze przy wywołaniu tej metody nic się nie stanie. Trzeba jedynie linię 41 wrzucić w if-a o zanegowanym warunku

2021-04-29 12:16 UTC, EmilSroka commented on library/src/ui/index.js
> +      }
Tutaj można pomyśleć o zanegowaniu warunku i daniu return (tak jak było w `setState`) Kwestia tylko czytelności. Coś ala to:
```
if (this.children == null || position > this.children.length) return;
if (position == this.children.length) {
  this.ref.appendChild(child);
} else {
  this.ref.insertBefore(child, this.children[position]);
}
this.children.splice(position, 0, child);
```
Myślałem nad eliminacją jeszcze tego `else`, ale zmieniało by to logikę a nie wiem czy dużo czytelniejsze by to było

2021-04-29 12:16 UTC, EmilSroka commented on library/src/ui/index.js
> +    },
Tutaj analogicznie można by zagnieżdżenie wyeliminować. Tylko pomysł podrzucam.

2021-04-29 12:16 UTC, EmilSroka commented on library/src/ui/index.js
> +      }
I tu też można. A czy jak wytniesz element z tablicy, to chyba już go tam nie będzie. W sensie kolejność `splice` i `destroy` chyba jest zła. I to samo było by w `removeChild`. Można by w sumie uogólnić logikę. Pobrać element z tablicy i wywołać `removeChild`. Usunie wtedy wszystkie instancje komponentu, ale z założenia komponent powinien być użyty raz per instancja.

2021-04-30 13:56 UTC, EmilSroka reviewed
LGTM

2021-04-30 13:59 UTC, EmilSroka commented
@HubMiz ustawione jest na dwa zatwierdzenia. Musimy to przedyskutować czy jest to konieczne. Jak znajdziesz czas to przepatrz - nawet tak pobieżnie - zmiany

2021-05-01 08:16 UTC, HubMiz approved these changes

2021-05-01 13:08 UTC, merged