feat: add create and remove table mechanism (WIP)
EmilSroka/CoNDeT pull request #68
Opened 2021-05-27 10:03 UTC by M1LO234

2021-05-27 18:08 UTC, EmilSroka requested changes
Przenieś logikę dodawani tabel do funkcji i spana jako osoby komponent. Ja jutro zdebuguję te błędy z przesuwaniem

2021-05-27 18:08 UTC, EmilSroka commented on library/src/ui/table/editMode.js
> +    this.table.ref.appendChild(this.removeTableElement(table.id));
Nie zadziała ze zmianą trybu, bo wstawiasz to jednorazowo. Zrób komponent np. DeleteTableBtnComponent i przenieś tam logikę odpowiedzialną za tego spana. I w komponencie `NameComponent` renderuj go tylko w trybie edycji. Aby móc usunąć tabelę, podaj id tabeli w dół jako propsy `NameComponent`. Możesz przenieść logikę eventów do oddzielnej strategii (ale ponieważ on i tak będzie renderowany w trybie edycji to nie musisz)

2021-05-27 18:08 UTC, EmilSroka commented on library/src/ui/table/editMode.js
> +  };
Tak jak pisałem wyżej, zrobić z tego komponent

2021-05-29 15:49 UTC, EmilSroka requested changes
Kilka drobnych uwag. Część kodu zmienię ja (jak będę integrował z moimi zmianami). Popraw je proszę i zrób CR moich zmian. I jak zrobisz te obie rzeczy to ja zrobię rebase i rozwiąże konflikty które na 100% się pojawią

2021-05-29 15:49 UTC, EmilSroka commented on library/src/data/index.js
> +        if (tableId == newState[i].id) {
`===`

2021-05-29 15:49 UTC, EmilSroka commented on library/src/index.js
> +    addTable: addTable,
Tu jest chyba niepotrzebne. A przynajmniej przy obecnych założeniach

2021-05-29 15:49 UTC, EmilSroka commented on library/src/index.js
> +  }
Można przerobić, aby funkcja przyjmowała jeden parametr (common) i przenieść do core. W tym pliku powinno być jak najmniej, bo jest on na wysokim poziomie abstrakcji, a ta funkcja jest niskopoziomowa

EDIT:  
Ponieważ podajesz ją jako `addTable: addTable,` to trzeba zrobić function factory która jest funkcją i przyjmuje `common` i zwraca tą funkcję

2021-05-29 15:49 UTC, EmilSroka commented on library/src/ui/display/editMode.js
> +
To można usunąć bo nie jest potrzebne

2021-05-29 15:49 UTC, EmilSroka commented on library/src/ui/table.js
> +    this.ref.className = "corner-element";
Można zmienić na `delete-table-btn`. Czysto teoretycznie nazwa klasy nie powinna mówić jak wygląda ani gdzie jest umieszczony dany element. Obecnie są różne podejścia, np. [utility first](https://tailwindcss.com/docs/utility-first). Więc kwestia dyskusyjna.

2021-05-30 14:08 UTC, HubMiz approved these changes

2021-05-30 14:39 UTC, EmilSroka approved these changes

2021-05-30 14:40 UTC, merged